### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by hyangl** [truechain/truechain-engineering-code#37]
when using send_transaction to send transactions to the node at a long time, it will be killed for out of memory.

```
INFO [12-14|20:46:15.708] start to mine                            block=9236 fruits=0     fast=584698 diff=10000 fdiff=100
INFO [12-14|20:46:15.786] Submitted transaction                    fullhash=0xc5dfbcb081f5ff9b51d4dfee3a495677ac22ca52db97c9bcec3273cd0d7e5fba recipient=0xcB35a719b05180f301B4214dF62Fb60f9d0977A9
INFO [12-14|20:46:16.780] Submitted transaction                    fullhash=0xbd683bdf19846605865c8d62147e5a8efc276284dff9b0cc85106ebafba84d8a recipient=0x91a829056D1e49fC0aF8758565A3fB24f0c2CFCa
INFO [12-14|20:46:17.961] Submitted transaction                    fullhash=0x95bdae5eb920de31baa2463ee3a208097aaac97170760f3427ab6cfb24347a06 recipient=0x63FC432886B6CC161ef809F8f8Bc03cd36CD788e
INFO [12-14|20:46:19.725] 馃崚  mined fruit                           number=584698 diff=100   hash=31802b鈥?b26ee signs=4
INFO [12-14|20:46:19.728] ____Commit new mining work               number=9236   uncles=0 fruits=0     fastblock=584699 diff=10000 fdiff=100 elapsed=3.090ms
INFO [12-14|20:46:19.745] start to mine                            block=9236 fruits=0     fast=584699 diff=10000 fdiff=100
INFO [12-14|20:46:20.089] Submitted transaction                    fullhash=0x15d8dd9e55edd72497b30035d7a30aa4acd2a23f19f3c7ac69bbdbe717370407 recipient=0x2605Ff568E6b277ab9a6C756c02C143BB473E3Ae
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x10c822b, 0x16)
	/usr/lib/go-1.10/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc5d0a70000, 0x10000000, 0x828200, 0x1e215d8)
	/usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1e07a40, 0x10000000, 0x7f41015ef090)
	/usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1e07a40, 0x8000, 0x0)
	/usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x1e07a40, 0x8000, 0x1e215e8, 0x7f41237fdde8)
	/usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x1e07a40, 0x8000, 0x420101, 0xc416143dff)
	/usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x1e07a40, 0x8000, 0x7f4123010101, 0x429c2c)
	/usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x10000000, 0x460101, 0x7f412c84e000)
	/usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x7f4100000000)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/lib/go-1.10/src/runtime/proc.go:1170

goroutine 1157071 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc5ca888c18 sp=0xc5ca888c10 pc=0x46dbd0
runtime.mallocgc(0x10000000, 0xeeec60, 0x1, 0xc5382cc000)
	/usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc5ca888cb8 sp=0xc5ca888c18 pc=0x426202
runtime.makeslice(0xeeec60, 0x4000000, 0x4000000, 0xc5382cc000, 0x200, 0x200)
	/usr/lib/go-1.10/src/runtime/slice.go:61 +0x77 fp=0xc5ca888ce8 sp=0xc5ca888cb8 pc=0x4578f7
github.com/truechain/truechain-engineering-code/vendor/golang.org/x/crypto/scrypt.Key(0xc4683110e8, 0x5, 0x8, 0xc49e086dc0, 0x20, 0x40, 0x40000, 0x8, 0x1, 0x20, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/golang.org/x/crypto/scrypt/scrypt.go:236 +0x152 fp=0xc5ca888da8 sp=0xc5ca888ce8 pc=0x6e7212
github.com/truechain/truechain-engineering-code/accounts/keystore.getKDFKey(0xc468311080, 0xb, 0xc49e086c80, 0x40, 0xc4b895a2a0, 0x20, 0xc468311090, 0x6, 0xc483500db0, 0xc49e086d00, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore_passphrase.go:330 +0x6a4 fp=0xc5ca888eb0 sp=0xc5ca888da8 pc=0x703914
github.com/truechain/truechain-engineering-code/accounts/keystore.DecryptDataV3(0xc468311080, 0xb, 0xc49e086c80, 0x40, 0xc4b895a2a0, 0x20, 0xc468311090, 0x6, 0xc483500db0, 0xc49e086d00, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore_passphrase.go:255 +0x28a fp=0xc5ca888fe8 sp=0xc5ca888eb0 pc=0x70264a
github.com/truechain/truechain-engineering-code/accounts/keystore.decryptKeyV3(0xc4a4b8fb00, 0xc468310f66, 0x5, 0xeae460, 0xc4a4b8fb00, 0x0, 0x0, 0xc4ee98fe50, 0x0, 0x0, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore_passphrase.go:277 +0xd1 fp=0xc5ca8890b0 sp=0xc5ca888fe8 pc=0x702a81
github.com/truechain/truechain-engineering-code/accounts/keystore.DecryptKey(0xc42f25cc00, 0x1eb, 0x3eb, 0xc468310f66, 0x5, 0x0, 0x0, 0xc4202586d8)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore_passphrase.go:222 +0x1bf fp=0xc5ca889168 sp=0xc5ca8890b0 pc=0x7020bf
github.com/truechain/truechain-engineering-code/accounts/keystore.keyStorePassphrase.GetKey(0xc4200da5f0, 0x4f, 0x40000, 0x1, 0x0, 0xdd7542173075357c, 0x18719fb81963e430, 0xf7e45662, 0xc4202b4fa0, 0x9d, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore_passphrase.go:88 +0x9c fp=0xc5ca889210 sp=0xc5ca889168 pc=0x7008fc
github.com/truechain/truechain-engineering-code/accounts/keystore.(*keyStorePassphrase).GetKey(0xc422468a20, 0xdd7542173075357c, 0x18719fb81963e430, 0xf7e45662, 0xc4202b4fa0, 0x9d, 0xc468310f66, 0x5, 0xdd7542173075357c, 0x18719fb81963e430, ...)
	<autogenerated>:1 +0xb8 fp=0xc5ca889298 sp=0xc5ca889210 pc=0x706be8
github.com/truechain/truechain-engineering-code/accounts/keystore.(*KeyStore).getDecryptedKey(0xc4224ee4b0, 0xdd7542173075357c, 0x18719fb81963e430, 0xf7e45662, 0x10b7b89, 0x8, 0xc4202b4fa0, 0x9d, 0xc468310f66, 0x5, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore.go:382 +0x1f0 fp=0xc5ca889368 sp=0xc5ca889298 pc=0x6ff5f0
github.com/truechain/truechain-engineering-code/accounts/keystore.(*KeyStore).TimedUnlock(0xc4224ee4b0, 0xdd7542173075357c, 0x18719fb81963e430, 0xf7e45662, 0x0, 0x0, 0x0, 0x0, 0xc468310f66, 0x5, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore.go:340 +0xb6 fp=0xc5ca889470 sp=0xc5ca889368 pc=0x6fee86
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PrivateAccountAPI).UnlockAccount(0xc42a3c1e20, 0xdd7542173075357c, 0x18719fb81963e430, 0xf7e45662, 0xc468310f66, 0x5, 0xc468310f80, 0x0, 0x0, 0x0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:404 +0x174 fp=0xc5ca889538 sp=0xc5ca889470 pc=0xa94944
runtime.call128(0xc42aaaacf0, 0xc42f8dfe48, 0xc4ee98fe00, 0x3800000050)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:575 +0x52 fp=0xc5ca8895c8 sp=0xc5ca889538 pc=0x46e0b2
reflect.Value.call(0xc42a5dce00, 0xc42f8dfe48, 0x13, 0x10b257f, 0x4, 0xc4e2039f80, 0x4, 0x4, 0x3, 0x48, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969 fp=0xc5ca889888 sp=0xc5ca8895c8 pc=0x4cb899
reflect.Value.Call(0xc42a5dce00, 0xc42f8dfe48, 0x13, 0xc4e2039f80, 0x4, 0x4, 0x3, 0x3, 0x3)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4 fp=0xc5ca8898f0 sp=0xc5ca889888 pc=0x4cae14
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc42a6b5ca0, 0x122a120, 0xc45711af40, 0x12303a0, 0xc4ee98fd10, 0xc471229920, 0xc4ee98fd80, 0x0, 0xf3d500)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676 fp=0xc5ca889a68 sp=0xc5ca8898f0 pc=0x828d86
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc42a6b5ca0, 0x122a120, 0xc45711af40, 0x12303a0, 0xc4ee98fd10, 0xc471229920)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6 fp=0xc5ca889ad8 sp=0xc5ca889a68 pc=0x8298a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc42a6b5ca0, 0x122a1e0, 0xc46a8d3da0, 0x12303a0, 0xc4ee98fd10, 0x10bc101, 0x1, 0x0, 0x0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c fp=0xc5ca889c08 sp=0xc5ca889ad8 pc=0x827adc
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc42a6b5ca0, 0x122a1e0, 0xc46a8d3da0, 0x12303a0, 0xc4ee98fd10, 0x1)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65 fp=0xc5ca889c60 sp=0xc5ca889c08 pc=0x828295
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc42a6b5ca0, 0x12289a0, 0xc5a0d820e0, 0xc459b6d400)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420 fp=0xc5ca889cf8 sp=0xc5ca889c60 pc=0x822580
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc42a838c40, 0x12289a0, 0xc5a0d820e0, 0xc459b6d400)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:257 +0x204 fp=0xc5ca889d58 sp=0xc5ca889cf8 pc=0x822de4
net/http.serverHandler.ServeHTTP(0xc42a757a00, 0x12289a0, 0xc5a0d820e0, 0xc459b6d400)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc fp=0xc5ca889d88 sp=0xc5ca889d58 pc=0x7e39ac
net/http.(*conn).serve(0xc47f69d860, 0x122a120, 0xc4354ab740)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651 fp=0xc5ca889fc8 sp=0xc5ca889d88 pc=0x7dfb01
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc5ca889fd0 sp=0xc5ca889fc8 pc=0x470761
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

goroutine 1 [select, 140 minutes]:
github.com/truechain/truechain-engineering-code/console.(*Console).Interactive(0xc42fea90a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/console/console.go:328 +0x29d
main.localConsole(0xc4201006e0, 0x0, 0x0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/cmd/getrue/consolecmd.go:95 +0x39a
github.com/truechain/truechain-engineering-code/cmd/utils.MigrateFlags.func1(0xc4201006e0, 0x1010100, 0xc4201006e0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/cmd/utils/flags.go:1398 +0x103
github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xf09ba0, 0xc4202acc00, 0xc4201006e0, 0xc4200d5900, 0x0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x10b607e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10e0e71, 0x2b, 0x0, ...)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa36
github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200c5a00, 0xc4200b6000, 0x12, 0x12, 0x0, 0x0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a0
main.main()
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/cmd/getrue/main.go:230 +0x55

goroutine 20 [chan receive]:
github.com/truechain/truechain-engineering-code/metrics.(*meterArbiter).tick(0x1df4ec0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:250 +0x78
created by github.com/truechain/truechain-engineering-code/metrics.NewMeter
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:44 +0x10b

goroutine 21 [chan receive, 140 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc4200d4180, 0xc4200d40c0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xf2

goroutine 22 [chan receive, 140 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc4200d4180, 0xc4200d4120)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x11e

goroutine 23 [syscall, 140 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x41

goroutine 24 [chan receive, 1 minutes]:
github.com/truechain/truechain-engineering-code/core.(*txSenderCacher).cache(0xc4200a5710)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/tx_cacher.go:63 +0x97
created by github.com/truechain/truechain-engineering-code/core.newTxSenderCacher
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/tx_cacher.go:55 +0xa4

goroutine 25 [chan receive, 1 minutes]:
github.com/truechain/truechain-engineering-code/core.(*txSenderCacher).cache(0xc4200a5710)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/tx_cacher.go:63 +0x97
created by github.com/truechain/truechain-engineering-code/core.newTxSenderCacher
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/tx_cacher.go:55 +0xa4

goroutine 30 [syscall, 140 minutes]:
syscall.Syscall6(0xe8, 0xb, 0xc4201bef6c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0xc4201bef40, 0x1, 0x8a5afe)
	/usr/lib/go-1.10/src/syscall/asm_linux_amd64.s:44 +0x5
github.com/truechain/truechain-engineering-code/vendor/golang.org/x/sys/unix.EpollWait(0xb, 0xc4201bef6c, 0x1, 0x1, 0xffffffffffffffff, 0xc4201befa8, 0x4197ec, 0xc4200943b8)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1529 +0x7a
github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).loop(0xc420104000, 0xc42021a060)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:194 +0x8b
created by github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:134 +0x128

goroutine 8 [select, 140 minutes, locked to thread]:
runtime.gopark(0x11068a0, 0x0, 0x10b5363, 0x6, 0x18, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4201c0f50, 0xc4200945a0)
	/usr/lib/go-1.10/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 9 [semacquire]:
runtime.ReadMemStats(0xc42245b800)
	/usr/lib/go-1.10/src/runtime/mstats.go:458 +0x36
github.com/truechain/truechain-engineering-code/metrics.CollectProcessMetrics(0xb2d05e00)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/metrics.go:74 +0x393
created by main.init.0.func1
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/cmd/getrue/main.go:216 +0x275

goroutine 11 [select, 140 minutes]:
github.com/truechain/truechain-engineering-code/accounts/keystore.(*watcher).loop(0xc42247e1a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/watch.go:94 +0x4a0
created by github.com/truechain/truechain-engineering-code/accounts/keystore.(*watcher).start
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/watch.go:52 +0x5d

goroutine 31 [chan receive, 140 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc420104000, 0xc42021a060)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0xae
created by github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x17b

goroutine 32 [chan receive, 140 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc420104000, 0xc42021a060)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0xae
created by github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x17b

goroutine 12 [select]:
github.com/truechain/truechain-engineering-code/accounts/keystore.(*KeyStore).updater(0xc4224ee4b0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore.go:203 +0xf0
created by github.com/truechain/truechain-engineering-code/accounts/keystore.(*KeyStore).Subscribe
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/keystore/keystore.go:190 +0x122

goroutine 13 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/lib/go-1.10/src/runtime/time.go:102 +0x166
github.com/truechain/truechain-engineering-code/accounts/usbwallet.(*Hub).updater(0xc422444500)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/usbwallet/hub.go:224 +0x3e
created by github.com/truechain/truechain-engineering-code/accounts/usbwallet.(*Hub).Subscribe
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/usbwallet/hub.go:213 +0x122

goroutine 14 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/lib/go-1.10/src/runtime/time.go:102 +0x166
github.com/truechain/truechain-engineering-code/accounts/usbwallet.(*Hub).updater(0xc422444640)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/usbwallet/hub.go:224 +0x3e
created by github.com/truechain/truechain-engineering-code/accounts/usbwallet.(*Hub).Subscribe
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/usbwallet/hub.go:213 +0x122

goroutine 15 [select, 140 minutes]:
github.com/truechain/truechain-engineering-code/accounts.(*Manager).update(0xc422470c30)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/manager.go:95 +0x1c6
created by github.com/truechain/truechain-engineering-code/accounts.NewManager
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/accounts/manager.go:68 +0x54c

goroutine 16 [select]:
github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc420262620)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x152
created by github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x171

goroutine 34 [select, 13 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4224941a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0xff
created by github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x49d

goroutine 35 [select]:
github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4224941a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x127
created by github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x4bf

goroutine 36 [select, 13 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4224941a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x277
created by github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x627

goroutine 37 [select, 140 minutes]:
github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4224941a0)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x15d
created by github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x649

goroutine 38 [select]:
github.com/truechain/truechain-engineering-code/ethdb.(*LDBDatabase).meter(0xc4200f0370, 0xb2d05e00)
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/ethdb/database.go:361 +0x19b5
created by github.com/truechain/truechain-engineering-code/ethdb.(*LDBDatabase).Meter
	/root/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/ethdb/database.go:177 +0x1b8

goroutine 39 [select, 140 minutes]:
```

**Comment by BiyunZeng** [comment]
fixed it by commit cc7c0d72b620f0e8df340b4e78aec97a28c44fb8 [cc7c0d72]
