### ISSUE TITLE
worker- invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hyangl** [truechain/truechain-engineering-code#66]
```
INFO [01-19|06:51:48.034] Validate new snail body                  block=342 hash=8efa3e…186d63 fruits=2ebe44…834054 first=20853 count=60
INFO [01-19|06:51:48.034] Write new snail canonical block...       number=342   hash=8efa3e…186d63
INFO [01-19|06:51:48.035] Inserted new snail block                 number=342   hash=8efa3e…186d63 fts=60 elapsed=786.811ms
INFO [01-19|06:51:48.035] Imported new snail chain segment         blocks=1 fts=60 elapsed=787.009ms number=342   hash=8efa3e…186d63 fruit=20853
INFO [01-19|06:51:48.035] -----------------get download info DoneEvent,FailedEvent 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xac4a2a]

goroutine 59 [running]:
github.com/truechain/truechain-engineering-code/core/types.(*SnailBlock).Fruits(...)
	/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/types/block.go:788
github.com/truechain/truechain-engineering-code/miner.(*worker).update(0xc42b23ac40)
	/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/miner/worker.go:337 +0x4ba
created by github.com/truechain/truechain-engineering-code/miner.newWorker
	/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/miner/worker.go:186 +0x642
```

**Comment by BiyunZeng** [comment]
fixed it by cc7c0d72b620f0e8df340b4e78aec97a28c44fb8
