### ISSUE TITLE
vm.opDifficulty error

### ISSUE THREAD

**Issue by hyangl** [truechain/truechain-engineering-code#83]
```
INFO [05-10|13:54:09.050] Imported new fast chain segment          blocks=2   txs=0  mgas=0.000 elapsed=141.139ms mgasps=0.000  number=240146 hash=2fca3c…5d33ea age=2w3d19h cache=12.55kB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x86fce7]

goroutine 1303 [running]:
math/big.(*Int).Set(...)
        /opt/go/src/math/big/int.go:68
github.com/truechain/truechain-engineering-code/core/vm.opDifficulty(0xc446001400, 0xc4448ae000, 0xc442718180, 0xc44a5afc60, 0xc44a5afca0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/vm/instructions.go:591 +0x87
github.com/truechain/truechain-engineering-code/core/vm.(*EVMInterpreter).Run(0xc4448ae000, 0xc442718180, 0x0, 0x0, 0x0, 0x10b5500, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/vm/interpreter.go:254 +0x49e
github.com/truechain/truechain-engineering-code/core/vm.run(0xc44b1fe000, 0xc442718180, 0x0, 0x0, 0x0, 0x68700, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/vm/evm.go:61 +0x1f2
github.com/truechain/truechain-engineering-code/core/vm.(*EVM).create(0xc44b1fe000, 0x128f840, 0xc442866b80, 0xc44baa81b8, 0x68790, 0xc44a5a8580, 0x6c611b21f42e8914, 0xf71868180ac6ea7e, 0x18719fb87d59a776, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/vm/evm.go:408 +0x693
github.com/truechain/truechain-engineering-code/core/vm.(*EVM).Create(0xc44b1fe000, 0x128f840, 0xc442866b80, 0xc4200d06e0, 0x142, 0x142, 0x68790, 0xc44a5a8580, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/vm/evm.go:448 +0x1fa
github.com/truechain/truechain-engineering-code/core.(*StateTransition).TransitionDb(0xc44a847490, 0x12a11e0, 0xc424891500, 0xc446001120, 0xc44a847490, 0xc424891500, 0xc424891500, 0x10e3be0)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/state_transition.go:231 +0x70f
github.com/truechain/truechain-engineering-code/core.ApplyMessage(0xc44b1fe000, 0x12a11e0, 0xc424891500, 0xc446001120, 0x18719fb81963e430, 0xf7e45662, 0xc44a5af9a0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/state_transition.go:135 +0x5b
github.com/truechain/truechain-engineering-code/core.ApplyTransaction(0x1abe5c0, 0x1291700, 0xc422370000, 0xc446001120, 0xc42b89cee0, 0xc44563ed80, 0xc42ade0000, 0xc44baafc38, 0xc44a5af800, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/state_processor.go:103 +0x2de
github.com/truechain/truechain-engineering-code/core.(*StateProcessor).Process(0xc42000cbc0, 0xc424b28b40, 0xc42b89cee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/state_processor.go:70 +0x3b5
github.com/truechain/truechain-engineering-code/core.(*BlockChain).insertChain(0xc422370000, 0xc424b59e90, 0x6, 0x6, 0xe4037abe363b8601, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/blockchain.go:1307 +0xacf
github.com/truechain/truechain-engineering-code/core.(*BlockChain).InsertChain(0xc422370000, 0xc424b59e90, 0x6, 0x6, 0xc424b0ca20, 0x5, 0x6)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/core/blockchain.go:1195 +0xd6c
github.com/truechain/truechain-engineering-code/etrue/fastdownloader.(*Downloader).importBlockResults(0xc4200cb860, 0xc424b59e30, 0x6, 0x6, 0x6, 0x0)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/etrue/fastdownloader/downloader.go:1159 +0x4d5
github.com/truechain/truechain-engineering-code/etrue/fastdownloader.(*Downloader).processFullSyncContent(0xc4200cb860, 0x128dc00, 0xc42c1f4f98)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/etrue/fastdownloader/downloader.go:1132 +0x79
github.com/truechain/truechain-engineering-code/etrue/fastdownloader.(*Downloader).(github.com/truechain/truechain-engineering-code/etrue/fastdownloader.processFullSyncContent)-fm(0x8, 0x11625b0)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/etrue/fastdownloader/downloader.go:472 +0x2a
github.com/truechain/truechain-engineering-code/etrue/fastdownloader.(*Downloader).spawnSync.func1(0xc4200cb860, 0xc43051a2a0, 0xc43dab6b20)
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/etrue/fastdownloader/downloader.go:487 +0x59
created by github.com/truechain/truechain-engineering-code/etrue/fastdownloader.(*Downloader).spawnSync
        /home/ubuntu/goSpace/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/etrue/fastdownloader/downloader.go:485 +0xaf
```

**Comment by shuxunyer** [comment]
solved
