### ISSUE TITLE
too many go routines when sending a lot of transactions through rpc

### ISSUE THREAD

**Issue by hyangl** [truechain/truechain-engineering-code#87]
getrue  version 1.0.1

```
goroutine 104636837 [semacquire, 30 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2dd96b07bf100)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc465360460, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc4ddd408c0, 0x12a4fe0, 0xc4349aec20, 0xc4754011e0, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc4ddd408c0, 0xc5245508f0, 0xaf, 0xaf, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc470a43ec0, 0x3, 0x4, 0x1, 0xc470a43ec0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc470a43ec0, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc4ddd408c0, 0x129fcc0, 0xc42a465a90, 0xc470a43c80, 0xc42a465ce0, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc4ddd408c0, 0x129fcc0, 0xc42a465a90, 0xc470a43c80)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc467e27f20, 0x129fcc0, 0xc42a465a90, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc467e27f20, 0x129fcc0, 0xc42a465a90, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc4c5f162a0, 0xc470de9300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc4c5f162a0, 0xc470de9300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc4c5f162a0, 0xc470de9300)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc4c5f162a0, 0xc470de9300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc4c5f162a0, 0xc470de9300)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc442219d60, 0x1299660, 0xc4ddd407c0)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

goroutine 104364885 [semacquire, 90 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2da531debb100)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc4d3643ea0, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc4f5115bc0, 0x12a4fe0, 0xc4349aec20, 0xc4435be270, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc4f5115bc0, 0xc47c3cd4a0, 0xaf, 0xaf, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc429a804e0, 0x3, 0x4, 0x1, 0xc429a804e0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc429a804e0, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc4f5115bc0, 0x129fcc0, 0xc46b0c5590, 0xc4b8c4eea0, 0xc464787c40, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc4f5115bc0, 0x129fcc0, 0xc46b0c5590, 0xc4b8c4eea0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc4b361ce40, 0x129fcc0, 0xc46b0c5590, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc4b361ce40, 0x129fcc0, 0xc46b0c5590, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc4ad591880, 0xc4b19eaf00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc4ad591880, 0xc4b19eaf00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc4ad591880, 0xc4b19eaf00)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc4ad591880, 0xc4b19eaf00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc4ad591880, 0xc4b19eaf00)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc4d3643e00, 0x1299660, 0xc4f5115ac0)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

goroutine 104612370 [semacquire, 35 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2dd5887900500)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc4c6865d60, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc44b70a7c0, 0x12a4fe0, 0xc4349aec20, 0xc49756b520, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc44b70a7c0, 0xc4ae38d130, 0xaf, 0xaf, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc441eddec0, 0x3, 0x4, 0x1, 0xc441eddec0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc441eddec0, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc44b70a7c0, 0x129fcc0, 0xc4e669c140, 0xc441edde00, 0xc4e669cc50, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc44b70a7c0, 0x129fcc0, 0xc4e669c140, 0xc441edde00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc44c92abd0, 0x129fcc0, 0xc4e669c140, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc44c92abd0, 0x129fcc0, 0xc4e669c140, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc4970e2e00, 0xc44c2e3700)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc4970e2e00, 0xc44c2e3700)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc4970e2e00, 0xc44c2e3700)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc4970e2e00, 0xc44c2e3700)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc4970e2e00, 0xc44c2e3700)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc4c68659a0, 0x1299660, 0xc44b70a6c0)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

goroutine 104632888 [semacquire, 30 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2dd893f28ba00)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc47a9febe0, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc42956c080, 0x12a4fe0, 0xc4349aec20, 0xc43d3cd380, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc42956c080, 0xc45c118840, 0xaf, 0xaf, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc442bf8f00, 0x3, 0x4, 0x1, 0xc442bf8f00, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc442bf8f00, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc42956c080, 0x129fcc0, 0xc4b76d9090, 0xc442bf8de0, 0xc4b76d9100, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc42956c080, 0x129fcc0, 0xc4b76d9090, 0xc442bf8de0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc45da04180, 0x129fcc0, 0xc4b76d9090, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc45da04180, 0x129fcc0, 0xc4b76d9090, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc4acd8fea0, 0xc440ebb300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc4acd8fea0, 0xc440ebb300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc4acd8fea0, 0xc440ebb300)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc4acd8fea0, 0xc440ebb300)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc4acd8fea0, 0xc440ebb300)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc47a9feb40, 0x1299660, 0xc42fab1a40)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

goroutine 104489648 [semacquire, 59 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2dbfd0efeba00)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc448031ea0, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc428c4f240, 0x12a4fe0, 0xc4349aec20, 0xc4d499c820, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc428c4f240, 0xc4f04d8790, 0xae, 0xae, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc52b92d7a0, 0x3, 0x4, 0x1, 0xc52b92d7a0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc52b92d7a0, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc428c4f240, 0x129fcc0, 0xc4bc1c2460, 0xc52b92d740, 0xc4bc1c24d0, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc428c4f240, 0x129fcc0, 0xc4bc1c2460, 0xc52b92d740)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc43cc166c0, 0x129fcc0, 0xc4bc1c2460, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc43cc166c0, 0x129fcc0, 0xc4bc1c2460, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc481755ea0, 0xc4e2bbe900)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc481755ea0, 0xc4e2bbe900)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc481755ea0, 0xc4e2bbe900)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc481755ea0, 0xc4e2bbe900)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc481755ea0, 0xc4e2bbe900)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc448031d60, 0x1299660, 0xc428c4f0c0)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

goroutine 104508571 [semacquire, 55 minutes]:
sync.runtime_SemacquireMutex(0x1ebed44, 0x2dc32d8419100)
	/usr/lib/go-1.10/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x1ebed40)
	/usr/lib/go-1.10/src/sync/rwmutex.go:93 +0x2d
github.com/truechain/truechain-engineering-code/metrics.NewMeter(0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:39 +0x56
github.com/truechain/truechain-engineering-code/metrics.NewRegisteredMeter(0x112092a, 0x16, 0x0, 0x0, 0xc4cb47edc0, 0xa0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/metrics/meter.go:54 +0x26
github.com/truechain/truechain-engineering-code/internal/trueapi.submitTransaction(0x1299660, 0xc47caf2cc0, 0x12a4fe0, 0xc4349aec20, 0xc47dcc9ba0, 0x0, 0x0, 0x0, 0x0, 0x1011ee0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1509 +0x76
github.com/truechain/truechain-engineering-code/internal/trueapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc446eb8240, 0x1299660, 0xc47caf2cc0, 0xc49cf6eb00, 0xaf, 0xaf, 0x0, 0x0, 0x0, 0x0, ...)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/internal/trueapi/api.go:1606 +0x32a
reflect.Value.call(0xc441f1d980, 0xc4315a43b0, 0x13, 0x110ae09, 0x4, 0xc4d8bc3e60, 0x3, 0x4, 0x1, 0xc4d8bc3e60, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc441f1d980, 0xc4315a43b0, 0x13, 0xc4d8bc3e60, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/truechain/truechain-engineering-code/rpc.(*Server).handle(0xc44a5d8720, 0x1299660, 0xc47caf2cc0, 0x129fcc0, 0xc4da4d8230, 0xc4d8bc3da0, 0xc4da4d82f0, 0x0, 0xf8e140)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:312 +0x676
github.com/truechain/truechain-engineering-code/rpc.(*Server).exec(0xc44a5d8720, 0x1299660, 0xc47caf2cc0, 0x129fcc0, 0xc4da4d8230, 0xc4d8bc3da0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:333 +0x1a6
github.com/truechain/truechain-engineering-code/rpc.(*Server).serveRequest(0xc44a5d8720, 0x1299720, 0xc4d0993200, 0x129fcc0, 0xc4da4d8230, 0x1114a01, 0x1, 0x0, 0x0)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:195 +0x39c
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeSingleRequest(0xc44a5d8720, 0x1299720, 0xc4d0993200, 0x129fcc0, 0xc4da4d8230, 0x1)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/server.go:226 +0x65
github.com/truechain/truechain-engineering-code/rpc.(*Server).ServeHTTP(0xc44a5d8720, 0x1297d60, 0xc46a45d880, 0xc459938d00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:199 +0x420
github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1297d60, 0xc46a45d880, 0xc459938d00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc44a5d9dc0, 0x1297d60, 0xc46a45d880, 0xc459938d00)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/truechain/truechain-engineering-code/rpc.(*virtualHostHandler).ServeHTTP(0xc44a5d9de0, 0x1297d60, 0xc46a45d880, 0xc459938d00)
	/root/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/rpc/http.go:263 +0x1c5
net/http.serverHandler.ServeHTTP(0xc44a5051e0, 0x1297d60, 0xc46a45d880, 0xc459938d00)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc4c9f7ca00, 0x1299660, 0xc487babe40)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b
```

**Comment by hyangl** [comment]
#86
